name: Flutter Lint Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"  # Adjust based on the Flutter version that includes Dart 3.5.4
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get  # Removed unnecessary working-directory

      - name: Run Flutter Lint Check
        run: flutter analyze
