name: Flutter Lint Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Dart Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Dart Analyze
        run: flutter analyze
